config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :comments
  resources :posts
  root "welcome#index"
  get 'welcome/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :telephone, :age, :gender, :address)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projetinho</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>

		<%= nav_bar fixed: :top, brand: "Projetinho Blogspot", brand_link: root_url do %>
			<%= menu_group do %>
    	    	<%= menu_item "Home", root_path %>
					
		        <%= menu_item "Sobre nós" %>

				<%= menu_divider %>

				<%= menu_item "Em alta" %>
<% 
=begin%>
								, about_us_path
								, contact_path
<%
=end
%>
				<%= form_tag busca_produto_path, method: :get, 
                    	class: "navbar-form navbar-right" do %>
        			<div class="form-group">
            			<%= text_field_tag :nome, nil, class: "form-control" %>
            			<%= button_to "Buscar", nil, class: "btn btn-default" %>
        			</div>
   				<% end %>

				<%= drop_down "Perfil" do %>
        			<%= menu_item "Meu perfil" %>
        			<%= menu_item "Configurações" %>
    				<%= drop_down_divider %>
    				<%= menu_item "Sair" %>
    			<% end %>
<%
=begin%>
								, latest_products_path
								, popular_products_path
								, discounted_products_path  
<%
=end
%>
			<% end %>	
			
		<% end %>
		
		<div class="container">
    <%= yield %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.number_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Telephone</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.telephone %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @user.telephone %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Bem-vindo ao projetinho estagiário nota 10 WallJobs!</h1>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Isso aqui tá hardcodado em HTML por enquanto, até pq a página de boas-vindas não é o foco.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>
<p>Teste de scroll da nav_bar.</p>